[[redirects]]
  from = "/2016/02/19/direct-link-to-image-in-google-photos-for-html-image-tag"
  to = "/posts/2016/02/19/direct-link-to-image-in-google-photos-for-html-image-tag"
 
 
 
 [[redirects]]
  from = "/2016/10/04/google-photos-shared-albums"
  to = "/posts/2016/10/04/google-photos-shared-albums"
  
  [[redirects]]
  from = "/:year/:month/:day/:slug"
  to = "/posts/:year-:month-:day-:slug"
  status = 301
  force = false
